### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-tests#1]
@bioconda/core, the tests are currently failing again because of instabilities in conda build. I could try to fix them myself again, but I prefer to wait some days until they have sorted them out.

I hope that they will introduce better quality control soon.

**Comment by bgruening** [comment]
Is this still an issue?
xref: https://github.com/bioconda/bioconda-recipes/issues/1744

**Comment by johanneskoester** [comment]
This was a different issue. I just forgot to close it. But we can use it to track the current issue on osx: [see here](https://travis-ci.org/bioconda/bioconda-tests/jobs/152190039#L217).
